### ISSUE TITLE
Continuation token and other response headers missing in cross-partition query

### ISSUE THREAD

**Issue by despian** [Azure/azure-cosmos-js#250]
Many response headers appear to be missing when running a cross-partition query.

Take the following examples:

```javascript
...
let options = {
  enableCrossPartitionQuery: true,
  maxItemCount: 1
}
let qi = client.database(database).container(container).items.query(query, options);
let results = await qi.executeNext();
```
<details><summary>results yields:</summary>

```
headers:
  x-ms-documentdb-query-metrics: {}
  x-ms-request-charge: 3.42
result: Array(1)
```
</details>
<br>

However, with the following:
```javascript
...
let options = {
  partitionKey: 'xxx',
  maxItemCount: 1
}
let qi = client.database(database).container(container).items.query(query, options);
let results = await qi.executeNext();
```
<details><summary>results yields:</summary>

```
headers:
  access-control-allow-credentials: "true"
  access-control-allow-origin: ""
  cache-control: "no-store, no-cache"
  content-type: "application/json"
  date: "Thu, 07 Mar 2019 18:16:13 GMT"
  lsn: "651"
  pragma: "no-cache"
  server: "Microsoft-HTTPAPI/2.0"
  transfer-encoding: "chunked"
  x-ms-activity-id: "61b533a7-868d-42ae-9124-cf48463a7393"
  x-ms-alt-content-path: "dbs/Soteria/colls/AlertDetails"
  x-ms-content-path: "VfQxAP6Rtms="
  x-ms-continuation: "xxx"
  x-ms-cosmos-llsn: "651"
  x-ms-cosmos-quorum-acked-llsn: "651"
  x-ms-current-replica-set-size: "1"
  x-ms-current-write-quorum: "1"
  x-ms-gatewayversion: "version=2.1.0.0"
  x-ms-global-committed-lsn: "-1"
  x-ms-item-count: "1"
  x-ms-last-state-change-utc: "Mon, 25 Feb 2019 13:07:27.425 GMT"
  x-ms-number-of-read-regions: "0"
  x-ms-quorum-acked-lsn: "651"
  x-ms-request-charge: "7.44"
  x-ms-resource-quota: "documentSize=10240;documentsSize=10485760;documentsCount=-1;collectionSize=10485760;"
  x-ms-resource-usage: "documentSize=1;documentsSize=1478;documentsCount=427;collectionSize=1590;"
  x-ms-schemaversion: "1.7"
  x-ms-serviceversion: "version=2.1.0.0"
  x-ms-session-token: "0:-1#651"
  x-ms-throttle-retry-count: 0
  x-ms-throttle-retry-wait-time-ms: 0
  x-ms-transport-request-id: "108"
  x-ms-xp-role: "0"
result: Array(1)
```
</details>
<br>

Why are there so few headers when doing a cross-partition query? Am I doing something wrong? I really need the continuation token header.

I'm using `"@azure/cosmos": "^2.1.2"` and `node v10.11.0`.
